### DISCUSSION TITLE
rust-analyzer not formatting, on save, from neovim v0.11

### DISCUSSION THREAD

**Discussion by madelaney** [rust-lang/rust-analyzer#19535] [Q&A] [answered]
With NeoVim v0.11, my code isn't formatted on save any more. If I run `cargo +nightly fmt` from the command line, the format runs just fine so I don't think it's my `.rustfmt.toml` (but I've included it for good measure).

From the lsp info screen, I see my configuration that tried to use the `+nightly` toolchain, and my other settings. I tried to look at the various neovim logs, but they yielded nothing.

I'm just not sure why format on save is no longer triggering. 

### nvim --version

```console
NVIM v0.11.0
Build type: Release
LuaJIT 2.1.1741730670
Run "nvim -V1 -v" for more info
```

### rust-analyzer --version

```console
rust-analyzer 0.3.2362-standalone (fb133c8c80 2025-03-29)
```

### .rustfmt.toml

```toml
edition = "2021"
fn_params_layout = "Vertical"
tab_spaces = 2
reorder_imports = true
reorder_modules = true
control_brace_style = "ClosingNextLine"
normalize_comments = true
normalize_doc_attributes = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
```

### LspConfig

```lua
vim.lsp.config('rust-analyzer', {
  settings = {
    ['rust-analyzer'] = {
      checkOnSave = true,
      formatOnSave = true,
      rustfmt = {
        extraArgs = { '+nightly', '--unstable-features' },
      },
    },
  },
})
```

### LspInfo

```lua
- LSP log level : DEBUG
- WARNING Log level DEBUG will cause degraded performance and high disk usage
- Log path: /Users//********/.local/state/nvim/lsp.log
- Log size: 584 KB

vim.lsp: Active Clients ~
- rust-analyzer (id: 1)
  - Version: 0.3.2362-standalone (fb133c8c80 2025-03-29)
  - Root directory: ~/work/gitlab.*********.*****/shared/clean
  - Command: { "/Users/********/.local/share/nvim/mason/bin/rust-analyzer", "--log-file", "/var/folders/l_/69sddwcd7rb9t2_gn7shtktm0000gn/T/nvim.mdelaney/xkI46G/4-rust-analyzer.log" }
  - Settings: {
      ["rust-analyzer"] = {
        checkOnSave = true,
        files = {
          watcher = "server"
        },
        formatOnSave = true,
        rustfmt = {
          extraArgs = { "+nightly", "--unstable-features" }
        }
      }
    }
  - Attached buffers: 2

vim.lsp: Enabled Configurations ~

vim.lsp: File Watcher ~
- file watching "(workspace/didChangeWatchedFiles)" disabled on all clients

vim.lsp: Position Encodings ~
- No buffers contain mixed position encodings

```
