### ISSUE TITLE
False `missing match arm` when using same crate with different features on different platforms

### ISSUE THREAD

**Issue by f32by** [rust-lang/rust-analyzer#11123]
**rust-analyzer version**: v0.3.876

**rustc version**: rustc 1.59.0-nightly (e2116acae 2021-12-05)

1. The library crate `lib_test`:

Cargo.toml:
```toml
# blabla

[features]
feat_macos = []
feat_linux = []
```

`lib.rs`:
```rust
pub enum Test1 {
    A, 
    #[cfg(feature = "feat_linux")]
    B,
    C,
}

pub enum Test2 {
    A
}

#[cfg(feature = "feat_macos")]
impl From<Test1> for Test2 {
    fn from(t: Test1) -> Self {
        match t {
            Test1::A | Test1::C => Test2::A
        }
    }
}

```

2. The executable crate `test`

Cargo.toml:
```toml
# blabla

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
lib_test = { path = "lib_test", features = ["feat_macos"] }

[target.'cfg(target_os = "linux")'.dependencies]
lib_test = { path = "lib_test", features = ["feat_linux"] }
```

3. Open `lib_test/lib.rs` in VSCode on macOS and rust-analyzer reports `missing-match-arm`:

<img width="648" alt="CleanShot 2021-12-27 at 15 01 45@2x" src="https://user-images.githubusercontent.com/12209857/147444258-6fb50372-5ad1-4ed9-b19d-aa8eb7cc47cb.png">
