### ISSUE TITLE
Unresolved import error for crate after adding lib.rs

### ISSUE THREAD

**Issue by swanandx** [rust-lang/rust-analyzer#11604]
I have a `lib.rs` file, which has the `pub async fn run()` function, but when I try to import it, rust-analyzer shows unresolved import error.
But it doesn't show any errors in `cargo check` / `clippy` , and it also builds successfully!

![image](https://user-images.githubusercontent.com/73115739/156416862-557e1c0a-fdfc-410b-821a-1d2891ea2a13.png)

Here is my `Cargo.toml` file:
```toml
[package]
name = "zero2prod"
version = "0.1.0"
..

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
..
```

**rust-analyzer version**: 4e72700e3 2022-02-28 stable

**rustc version**: rustc 1.59.0 (9d1b2106e 2022-02-23)
