### ISSUE TITLE
macro behind optional flag is still checked

### ISSUE THREAD

**Issue by Emilgardis** [rust-lang/rust-analyzer#12192]
![image](https://user-images.githubusercontent.com/1502855/167314723-4f05966a-771e-40ee-a9c0-9958d9c4a271.png)

### lib.rs
```rust
pub fn stuff() {
    #[cfg(f = "1")]
    tracing::dispatcher::set_global_default(todo!());
    #[cfg(f = "1")]
    tracing::info!(todo!());
}
```

### Cargo.toml
```toml
[package]
name = "cfg-stuff"
version = "0.1.0"
edition = "2021"
[dependencies]
tracing = {version = "0.1.34", optional = true }
```

gives `"unresolved macro tracing::info!"` on line 5, but no unresolved stuff on line 3
	
**rust-analyzer version**: 5d5bbec9b60010dd

**rustc version**: rustc 1.62.0-nightly (30f386087 2022-05-05)

**relevant settings**: `"rust-analyzer.procMacro.enable": true`
