### ISSUE TITLE
Unit tests in lib/core workspace parsed abnormally

### ISSUE THREAD

**Issue by Banyc** [rust-lang/rust-analyzer#12282]
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)

rust-analyzer version: 94fa8a653 2022-05-12 nightly

**rustc version**: (eg. output of `rustc -V`)

rustc 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

none

# File structure

- A
  - core
    - src/
    - Cargo.toml
  - B 
    - src/
    - Cargo.toml
  - C
    - src/
    - Cargo.toml
  - Cargo.lock
  - Cargo.toml

`A/Cargo.toml`:

```toml
[workspace]
members = [
    "core",
    "B",
    "C",
]

```

`A/core/Cargo.toml`:

```toml
[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```

`A/B/Cargo.toml`:

```toml
[package]
name = "B"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../core" }
```

`A/C/Cargo.toml`:

```toml
[package]
name = "C"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../core" }
```

# Issues

Unit tests written in files under `core/src` do not have `CodeLen` features like `Run Test | Debug` buttons. Worse still, the suggestions make little sense.

In comparisons, the unit tests in `B/src` work as expected. None of the issues happens here.
