### ISSUE TITLE
Error: Command failed: git --no-pager --git-dir

### ISSUE THREAD

**Issue by mylvghb** [rust-lang/rust-analyzer#12445]
**rust-analyzer version**: v0.3.1075

**rustc version**: rustc 1.61.0 (fe5b13d68 2022-05-18)

**cargo config file**: 
``` TOML
[source.crates-io]
replace-with = 'rsproxy'

[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"

[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"

[net]
git-fetch-with-cli = true
```

**Problem Description**

A recent occurrence

![image](https://user-images.githubusercontent.com/35945793/171538304-dd7b4782-1b4e-447b-b576-b94e84a55bbb.png)
