### ISSUE TITLE
Setting build flags in .cargo/config.toml breaks incremental compilation

### ISSUE THREAD

**Issue by MasonMcGill** [rust-lang/rust-analyzer#12688]
I'm working on a wasm/web_sys project, and when the rust-analyzer extension is enabled in VSCode, adding the following `.cargo/config.toml` file to my project causes every cargo run to rebuild the project from scratch (after blocking on "waiting for file lock on build directory" for a few seconds):

```toml
[build]
rustflags = ["--cfg=web_sys_unstable_apis"] # Enables experimental web APIs
```

Replacing "build" with "target.wasm32-unknown-unknown" solves the build problem, but causes rust-analyzer to emit errors when the experimental parts of web_sys are used.

**rust-analyzer version**: 0.0.0 (75b22326d 2022-07-03)
**rustc version**: 1.62.0 (a8314ef7d 2022-06-27)

**Comment by Veykril** [comment]
> Replacing "build" with "target.wasm32-unknown-unknown" solves the build problem, but causes rust-analyzer to emit errors when the experimental parts of web_sys are used.

What errors, setting the target would be the right choice here usually, you want r-a to build with the same environment as your normal builds to prevent these rebuilds (and r-a should honor the `.cargo/config.toml`)

**Comment by MasonMcGill** [comment]
Hi — thanks for getting back so quickly. Putting the rustflags in the target section I'd get error squigglies under symbols gated by `--cfg=web_sys_unstable_apis` (like those from the WebUSB API). Doing a bit more experimentation, I figured out that this config makes both the static analysis and the build command work as expected:

```toml
[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = ["--cfg=web_sys_unstable_apis"]
```

so at least for this project I no longer have an issue. I did spend a lot of time trying to figure this out, though—all the blog posts/stack overflow threads I could find suggested putting the rust flags in the build section—so this may be a UX issue for other, too.
