### ISSUE TITLE
The highlight of the link in docs seems mislocated

### ISSUE THREAD

**Issue by pan93412** [rust-lang/rust-analyzer#12912]
**rust-analyzer version**: `0.4.1145-standalone (fb5e49631 2022-07-29)`

**rustc version**: `rustc 1.63.0-beta.7 (12c5b1ef3 2022-07-22)`

**relevant settings**:

_rust-toolchain.toml_

```toml
[toolchain]
channel = "beta"
components = ["rust-src"]
profile = "default"
```

![telegram-cloud-photo-size-5-6280678913898295968-y](https://user-images.githubusercontent.com/28441561/181877929-6689309b-0e59-48e0-b4b6-1136ce3c7b05.jpg)

The highlight of the inline link of docs seems mislocated.
