### ISSUE TITLE
VSCode  can't show  `Run` or `Debug` button in  main.rs

### ISSUE THREAD

**Issue by zhuxiujia** [rust-lang/rust-analyzer#13240]
see this code on vscode
```toml
tokio = { version = "1.12", features = ["full"] }
log = "0.4"
fast_log = "1.5"
serde = { version = "1", features = ["derive"] }
rbs = { version = "0.1"}
rbatis = { version = "4.0"}
rbdc-sqlite = { version = "0.1" }
```

```rust
#[macro_use]
extern crate rbatis;

use rbatis::Rbatis;
use rbatis::rbdc::datetime::FastDateTime;
use rbatis::sql::page::PageRequest;
use rbdc_sqlite::driver::SqliteDriver;

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct BizActivity {
    pub id: Option<String>,
    pub name: Option<String>,
    pub pc_link: Option<String>,
    pub h5_link: Option<String>,
    pub pc_banner_img: Option<String>,
    pub h5_banner_img: Option<String>,
    pub sort: Option<String>,
    pub status: Option<i32>,
    pub remark: Option<String>,
    pub create_time: Option<FastDateTime>,
    pub version: Option<i64>,
    pub delete_flag: Option<i32>,
}

//crud!(BizActivity {},"biz_activity");//custom table name
//impl_select!(BizActivity{select_all_by_id(table_name:&str,id:&str) => "`where id = #{id}`"}); //custom table name
crud!(BizActivity {});
impl_select!(BizActivity{select_all_by_id(id:&str,name:&str) => "`where id = #{id} and name = #{name}`"});
impl_select!(BizActivity{select_by_id(id:&str) -> Option => "`where id = #{id} limit 1`"});
impl_update!(BizActivity{update_by_name(name:&str) => "`where id = '2'`"});
impl_delete!(BizActivity {delete_by_name(name:&str) => "`where name= '2'`"});
impl_select_page!(BizActivity{select_page() =>"
     if !sql.contains('count'):
       `order by create_time desc`"});
impl_select_page!(BizActivity{select_page_by_name(name:&str) =>"
     if name != null && name != '':
       `where name != #{name}`
     if name == '':
       `where name != ''`"});

#[tokio::main]
pub async fn main() {

}

```
