### ISSUE TITLE
[Question] how do I configure rust-analyzer for helix-editor or somehow give settings.json from a specific folder

### ISSUE THREAD

**Issue by boroicamarius** [rust-lang/rust-analyzer#13422]

**Comment by Velocity-** [comment]
https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers

**Comment by lnicola** [comment]
Thanks, @Velocity-, but that page doesn't make it clear how to configure the language servers. Anyway, this isn't our concern (each LSP client can use its own configuration syntax).

Maybe this will help, though: https://docs.helix-editor.com/languages.html#language-server-configuration.

**Comment by lnicola** [comment]
Here's an example, though:

```toml
# languages.toml
[[language]]
name = "rust"

[language.config]
cachePriming.enable = false
diagnostics.experimental.enable = true
```
