### ISSUE TITLE
Shows error "the trait `Try` is not implemented for `_` (rust-analyzer not-implemented)" with `anyhow` and `axum`, when the example compiles

### ISSUE THREAD

**Issue by PizzasBear** [rust-lang/rust-analyzer#13464]
The error ``the trait `Try` is not implemented for `_` (rust-analyzer not-implemented)`` is shown even though the example compiles.

main.rs:
```rust
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    axum::Server::bind(&"127.0.0.1:8080".parse().unwrap())
        .serve(axum::Router::new().into_make_service())
        .with_graceful_shutdown(async {})
        .await?;

    Ok(())
}

```
Cargo.toml:
```toml
[package]
name = "test-issue"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5"
anyhow = "1.0"
tokio = { version = "1.21", features = ["full"] }
```

**rust-analyzer version**: `0.3.1248-standalone`

**rustc version**: `rustc 1.64.0 (a55dd71d5 2022-09-19)`

**relevant settings**: Tested to work on neovim + coc.nvim and on VSCodium
