### ISSUE TITLE
Always uses main branch

### ISSUE THREAD

**Issue by botahamec** [rust-lang/rust-analyzer#13487]
I have this in my Cargo.toml

```toml
[dependencies]
# ...
texture_packer = { git = "https://github.com/botahamec/piston_texture_packer", branch = "u16" }
```

But I'm still getting a compiler error which should only appear on the main branch. I've tried restarting rust-analyzer, restarting VSCode, and running `cargo update`. None of that seems to fix it.

**rust-analyzer version**: rust-analyzer version: 0.4.1259-standalone (53b6d69e9 2022-10-24)

**rustc version**: 1.66.0-nightly (dcb376115 2022-10-20)
