### ISSUE TITLE
SeaORM macros show error but compiles when using a field with raw identifier

### ISSUE THREAD

**Issue by PizzasBear** [rust-lang/rust-analyzer#13706]
I tried using [SeaORM](https://www.sea-ql.org/SeaORM/) with a database that had a column named `type`. The generated bindings compiled but rust-analyzer showed a few errors, this example demonstrates that.

`src/main.rs`:
```rust
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "tbl")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub r#type: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

fn main() {
    let _ = ActiveModel {     // ERROR: missing structure fields:  - sea_orm  - ActiveValue
        id: sea_orm::ActiveValue::NotSet,
        r#type: sea_orm::ActiveValue::Set(0),     // ERROR: no such field
    };
}
```

`Cargo.toml`:
```toml
[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "0.10.5", features = ["macros"] }
```

**rust-analyzer version**: 0.3.1301-standalone

**rustc version**: rustc 1.65.0 (897e37553 2022-11-02)

**relevant settings**:
