### ISSUE TITLE
False positive errors on types/parameters gated by #[cfg(feature = ...)]

### ISSUE THREAD

**Issue by recatek** [rust-lang/rust-analyzer#14051]
**rust-analyzer version**: rust-analyzer version: 0.3.1377-standalone
**rustc version**: rustc 1.66.0 (69f9c33d7 2022-12-12)

When a `#[cfg(feature = ...)]` changes a type or function parameter, rust-analyzer displays incorrect errors where compiling is fine.

As an example, take these three crates in a workspace:

client/Cargo.toml
```toml
[package]
name = "client"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common", features = [ "client" ] }
```

client/src/main.rs
```rust
fn main() {
    common::do_thing(());
}
```

server/Cargo.toml
```toml
[package]
name = "server"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common", features = [ "server" ] }
```

server/src/main.rs
```rust
fn main() {
    common::do_thing(common::ServerThing);
}
```

common/Cargo.toml
```toml
[package]
name = "common"
version = "0.0.0"
edition = "2021"

[features]
client = []
server = []
```

common/src/lib.rs
```rust
#[cfg(feature = "server")]
pub struct ServerThing;

#[cfg(feature = "server")]
pub type ServerThingAlias = ServerThing;
#[cfg(not(feature = "server"))]
pub type ServerThingAlias = ();

pub fn do_thing(thing: ServerThingAlias) {}
```

Here rust-analyzer will highlight the `common::do_thing(());` line in client/src/main.rs with a mismatched types error, but building the client and server both successfully complete. An ignore option could work here as a fallback, see #13618.
