### ISSUE TITLE
rust-analyzer not taking into account default features?

### ISSUE THREAD

**Issue by LollipopFt** [rust-lang/rust-analyzer#14105]
hi, i have a file structure:
```
root
|-Cargo.toml
|-src/lib.rs
|-foo
  |-Cargo.toml
  |-src/main.rs
```

`root/Cargo.toml`:
```toml
[package]
name = "a"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "foo"
path = "foo/src/main.rs"

[features]
a = []
b = []
default = ["a"]
```

`foo/src/main.rs`:
```rs
fn main() {
    bar();
}

#[cfg(feature = "a")]
fn bar() {
    let a = "a";
    print!("test {a}");
}

#[cfg(feature = "b")]
fn bar() {
    let b = "b";
    print!("test {b}");
}
```

`cargo run --release` in the console outputs `test a`, but `rust-analyzer` gives the error:
```rs
#[cfg(feature = "a")] // code is inactive due to #[cfg] directives: feature = "a" is disabled
fn bar() {
    let a = "a";
    print!("test {a}");
}
```
and refuses to give any information when i hover over the variable `a`, giving `no information available` in neovim. is this expected behavior?
