### ISSUE TITLE
dev-dependencies on workspace member cause cyclic dependency issues

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#14167]
This issue is spread across several others, so let's make one big one out of it to better track it.
Yeah, the problem is that a crate can have a dev-dep onto itself:

https://github.com/rust-lang/rust-analyzer/issues/2414#issuecomment-561213070
> ```rust
> [package]
> name = "foo"
> version = "0.1.0"
> edition = "2018"
> 
> [dev-dependencies]
> foo = { path = "." }
> ```
> 
> The solution here is to start "duplicating" crates when lowering `cargo-metada` output to `CrateGraph`. In the above example, we should construct two `foo` crates, one with `cfg(test)` and one without, and make the required depednency edge. 

Issues in question:
https://github.com/rust-lang/rust-analyzer/issues/8330
https://github.com/rust-lang/rust-analyzer/issues/2414
https://github.com/rust-lang/rust-analyzer/issues/12407
https://github.com/rust-lang/rust-analyzer/issues/9574
https://github.com/rust-lang/rust-analyzer/issues/11410

**Comment by GilShoshan94** [comment]
Is it the same issue for crates that export proc_macro with other crates ?

I have a main crate `foo`, and another one `foo-derive` with the proc_macro.
I wanted to test `foo-derive` inside itself and to not have the tests moved to `foo` for the derive macro only.
But I need `foo` in the tests since the generate code used structs and traits from `foo` public API.

In `foo-derive` Cargo.toml:
```toml
[package]
name = "foo-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }

[dev-dependencies]
foo = { path = "../foo" }
trybuild = "1"
```

Is it inherently wrong to do that ? 

Beside an error (appears twice in a row) in the output of `Rust Analyzer Language Server` in vscode
> ```[ERROR project_model::workspace] cyclic deps: foo_derive(CrateId(76)) -> foo(CrateId(69)), alternative path: foo(CrateId(69)) -> foo_derive(CrateId(76))```

Everything seems to work well.
