### ISSUE TITLE
"Internal error, cycle detected" when the *ring* crate is used as a dependency

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust-analyzer#14305]
```
Internal error, cycle detected:

trait_impls_in_crate(CrateId(299))
impl_trait(ImplId(57519))
const_eval(ConstId(12178))
mir_body(ConstId(ConstId(12178)))
infer_query(ConstId(ConstId(12178)))
trait_solve_query((CrateId(299), Canonical { value: InEnvironment { environment: Env([]), goal: Implemented(Uint(Usize): TraitId(231)) }, binders: [] }))
trait_impls_in_deps(CrateId(299))
 (Internal Error)
```

**Cargo.toml**
```toml
[package]
name = "repro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = { version = "=0.16.20" }
```

(originally from `octocrab` -> `jsonwebtoken` -> *`ring`*)

**main.rs**

```rust
fn main() {
    println!("Hello, world!");
}
```

- `rust-analyzer 0.0.0 (8ce5a5393 2023-03-09)`
- `rustc 1.70.0-nightly (900c35403 2023-03-08)`
