### ISSUE TITLE
Unknown type in basic `esp32c3-hal`

### ISSUE THREAD

**Issue by lh123** [rust-lang/rust-analyzer#14876]
**rust-analyzer version**: rust-analyzer version: 0.0.0 (7ac161ce7 2023-05-21)

**rustc version**: rustc 1.69.0 (84c898d65 2023-04-16)

## `let system = peripherals.SYSTEM.split();` has `{unknown}` type

![image](https://github.com/rust-lang/rust-analyzer/assets/10697249/1350dd08-0be6-4aae-ac85-3b6b3fb2fbfd)

# 1. main.rs
```rust
#![no_std]
#![no_main]

use core::panic;

use esp32c3_hal::prelude::_esp_hal_system_SystemExt;
use esp32c3_hal::{entry, peripherals::Peripherals};

#[entry]
fn main() -> ! {
    let peripherals = Peripherals::take();
    let system = peripherals.SYSTEM.split();
    //  ^^^^^ system has unknown type
    drop(system);
    loop {}
}

#[panic_handler]
fn panic_handler(_: &panic::PanicInfo) -> ! {
    loop {}
}

```
# 2. Cargo.toml
```toml
[package]
name = "blink"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
esp32c3-hal = "0.9.0"

[profile.release]
debug = false

```
