### ISSUE TITLE
Autocomplete results in `thread 'Worker' has overflowed its stack`

### ISSUE THREAD

**Issue by 02alexander** [rust-lang/rust-analyzer#15236]
When VS-code tries to autocomplete `rerun::MsgSender::` the rust-analyzer crashes and produces the following error:
```
thread 'Worker' has overflowed its stack
fatal runtime error: stack overflow
```
It doesn't have a problem with autocompleting anything else from the `rerun` crate. Only `rerun::MsgSender`

src/main.rs:
```rust
fn main() {    
    rerun::MsgSender::
}
```
Cargo.toml:
```toml
[package]
name = "stackoverflow"
version = "0.1.0"
edition = "2021"

[dependencies]
rerun = "0.7.0"
```

**rust-analyzer version**: 0.4.1580

**rustc version**: rustc 1.70.0 (90c541806 2023-05-31)

**relevant settings**: None
