### ISSUE TITLE
vscode Incorrect  `Run`  button position

### ISSUE THREAD

**Issue by zhuxiujia** [rust-lang/rust-analyzer#15771]
[code_link](https://github.com/rbatis/example/blob/main/src/crud_map.rs)

![1697466399214](https://github.com/rust-lang/rust-analyzer/assets/3481148/70eb3af5-1c37-4b32-b9bf-7a0cb9f6b12a)

**Comment by zhuxiujia** [comment]
@lnicola  I can confirm that it was caused by multiple bin errors，
just like  this toml file
```toml
[package]
name = "example"
version = "0.1.0"
authors = ["zhuxiujia <zhuxiujia@qq.com>"]
edition = "2021"
publish = false


[[bin]]
name = "macro_proc_htmlsql"
path = "src/macro_proc_htmlsql.rs"

[[bin]]
name = "macro_proc_htmlsql_custom_func"
path = "src/macro_proc_htmlsql_custom_func.rs"

[[bin]]
name = "macro_proc_pysql"
path = "src/macro_proc_pysql.rs"

[[bin]]
name = "macro_proc_pysql_file"
path = "src/macro_proc_pysql_file.rs"
```
