### ISSUE TITLE
cargo.unsetTest setting not honored for primary package

### ISSUE THREAD

**Issue by LunarLambda** [rust-lang/rust-analyzer#15791]
**rust-analyzer version**: rust-analyzer 1.75.0-nightly (1c05d50 2023-10-21)

**rustc version**: rustc 1.75.0-nightly (1c05d50c8 2023-10-21)

I'm working on an embedded project which requires the nightly `-Z build-std` feature and only uses `core`. RA doesn't work on the main package (binary) due to throwing up ``error[E0463]: can't find crate for `test` ``. I tried including the main package name in the `unsetTest` setting (same name as in Cargo.toml) but to no avail.

`Cargo.toml`:
```toml
[package]
name = "xyz"
version = "0.1.0"
edition = "2021"
```
`src/main.rs`:
```rs
#![no_std]
#![no_main]

// ...
```
`.vscode/settings.json`:
```json
{
    "rust-analyzer.cargo.unsetTest": [
        "core",
        "xyz"
    ]
}
```
`.cargo/config.toml`:
```toml
[build]
target = "thumbv4t-none-eabi"

[unstable]
build-std = ["core"]
```
`rust-toolchain.toml`:
```toml
[toolchain]
channel = "nightly"
components = ["rust-src"]
```
