### ISSUE TITLE
RA VSCode extension not working on bin files.

### ISSUE THREAD

**Issue by CarlosHSF99** [rust-lang/rust-analyzer#15897]
I'm using the [rust-analyzer vscode extension](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer) and it works for the `src/lib.rs` file, but not for the `src/bin/foo.rs` and `src/bin/bar.rs` files. Cargo check works on both of these files.
I'm very new to Rust so it's likely that I'm doing something wrong.

Project structure:
```
.
├── Cargo.lock
├── Cargo.toml
├── rustfmt.toml
└── src
    ├── bin
    │   ├── foo.rs
    │   └── bar.rs
    ├── lib.rs
    └── main.rs
```

Cargo.toml:
```toml
[package]
name = "foobar"
version = "0.1.0"
edition = "2021"

[lib]
name = "local"
path = "src/lib.rs"

[[bin]]
name = "foo"
path = "src/bin/foo.rs"

[[bin]]
name = "bar"
path = "src/bin/bar.rs"

[dependencies]
anyhow = "1.0.75"
bitvec = "1.0.1"
threadpool = "1.8.1"
```
