### ISSUE TITLE
How to clean up the cache?

### ISSUE THREAD

**Issue by BasileCooke** [rust-lang/rust-analyzer#16236]
I'm on Ubuntu 22.04, using the rust-analyzer extenstion in a git-versionned workspace where a workspace package A depends on another B.

I made a change on B, adding a field to a struct, without changing the version in `cargo.toml`, the project builds correctly but the extension show an error.

If I change the version of the B package, the extension is fixed, but when I go back to the previous version, it shows up again.

I tried to use "cargo clean" but it doesn't change anything.

Where is the cache for rust analyzer and how to clean it?

Thanks!

EDIT: forgot to mention I'm using VS code

**Comment by mohe2015** [comment]
Did you already try reloading/restarting your editor?

**Comment by BasileCooke** [comment]
Thanks for you answers :smile: 

> Did you already try reloading/restarting your editor?

Of course, this hasn't change anything for me.

> There is no cache

I don't see how it could behave the way it does without some cache somewhere. It defenitely remember the old code.

> you might have edited Cargo's copy of B (under ~/.cargo/registry/src/, deleting that should be safe).

I tried to do `cargo clean`, then close vscode, then delete `~/.cargo/registry/cache`, `~/.cargo/registry/index` and `~/.cargo/registry/src`. Still have the issue. Was very hopeful for this one :/

**Comment by lnicola** [comment]
`cargo update -p B`?

**Comment by BasileCooke** [comment]
> `cargo update -p B`?

Didn't work :cry:

**Comment by lnicola** [comment]
Does `cargo build --all-targets` work?

**Comment by BasileCooke** [comment]
> Does `cargo build --all-targets` work?

Does not seem to work either :/

**Comment by lnicola** [comment]
You're on your own then. But remember that:

 - `Cargo.toml` can specify a SHA/branch/tag for `git` dependencies
 - `Cargo.lock` will store the SHA for those (`cargo update` should have bumped that though)

Also, you might want to check if you're using the workspace version of B, or if you're pulling it from crates.io.

**Comment by BasileCooke** [comment]
A and B are custom packages not pushed to crates.io. However if the commit sha1 is saved to `Cargo.lock` maybe the outdated code comes from the `.git` folder?

Is it safe to remove the `Cargo.lock` file?

**Comment by lnicola** [comment]
It will be created again, with the latest available versions. Keep the old one as a backup.

**Comment by BasileCooke** [comment]
Doesn't work though...

**Comment by mohe2015** [comment]
Can you show us your Cargo.toml files (or relevant excerpts)?

**Comment by BasileCooke** [comment]
I can show you a resume.

File architecture ->
```
.git
folder0/Cargo.toml
folder0/A/Cargo.toml
folder0/folder1/B/Cargo.toml
folder0/folder1/C/Cargo.toml
folder0/D/Cargo.toml
```

`folder0/Cargo.toml` ->
```toml
[workspace]
resolver = "2"

members = [
    "A",
    "folder1/B",
    "folder1/C",
]

exclude = ["D"]

[workspace.dependencies]
libLib = "=0.x.x"
```

`folder0/A/Cargo.toml` ->
```toml
[package]
name = "A"
version = "1.0.0"
authors = ["Me"]
edition = "2018"
description = "Main program"
homepage = "no_homepage"

[dependencies]
libLib .workspace = true

# Internal dependencies
B = { path = "../folder1/B/" }
C = { path = "../folder1/C/" }
```

`folder0/folder1/B/Cargo.toml` ->
```toml
[package]
name = "B"
version = "0.1.0"
authors = ["Me"]
edition = "2018"

[dependencies]
libLib.workspace = true

# Internal dependencies
C = { path = "../C/" }
```

`folder0/folder1/C/Cargo.toml` ->
```toml
[package]
name = "C"
version = "0.1.0"
edition = "2021"

[dependencies]
libLib.workspace = true
```

Don't know if its related or not but the `edition` is different in package C.

What happened is that the package B changed with a field added to a struct and the package A was updated accordingly. The code compiles but vscode shows an error in package A that says the field is missing.

Note: In the B changes, I did not change the version of the B package. When change it to, let's say, "0.1.1", vscode does not report the issue anymore. But if I change it back, the error is shown again.
