### ISSUE TITLE
Incorrect import suggestion when using `rhai`

### ISSUE THREAD

**Issue by Cerber-Ursi** [rust-lang/rust-analyzer#16436]
Got somewhat strange behavior when working with `rhai`. Here's the minimal example.

`Cargo.toml`:
```toml
[package]
name = "quick_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
rhai = "=1.16.3"
```
`main.rs`:
```rust
fn main() {
    let _: Rc<RefCell<()>> = todo!();
}
```

This code errors as expected, but when I try to use code actions to apply auto fixes, VSCode with RA offers to auto import `rhai::Shared` and `rhai::Locked`, instead of `std::rc::Rc` and `std::cell::RefCell`. `cargo check` shows suggestions correctly, so it's purely rust-analyzer problem.

**rust-analyzer version**: 0.3.1815-standalone

**rustc version**: 1.75.0 (82e1608df 2023-12-21)
