### ISSUE TITLE
[Question] rust-analyzer.exe missing in `1.77-x86_64-pc-windows-msvc`

### ISSUE THREAD

**Issue by jcs090218** [rust-lang/rust-analyzer#16966]
I'm playing the [Zed](https://github.com/zed-industries/zed), and they have the `rust-toolchain.toml` file:

```toml
[toolchain]
channel = "1.77"
profile = "minimal"
components = [ "rustfmt", "clippy" ]
targets = [ "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-linux-gnu", "wasm32-wasi" ]
```

When I tried the language server from Emacs through `lsp-mode`, I got the error:

```
Unknown binary 'rust-analyzer.exe' in official toolchain '1.77-x86_64-pc-windows-msvc'.
```

So my question is, why there isn't a `rust-analyzer.exe` in that toolchain? 🤔 Is there something I need to change with `lsp-mode`?
