### ISSUE TITLE
"file not included in module tree" diagnostic for file included using include! macro

### ISSUE THREAD

**Issue by komar007** [rust-lang/rust-analyzer#17044]
**rust-analyzer version**:  1.77.2 (25ef9e3 2024-04-09)

**rustc version**: 1.77.2 (25ef9e3d8 2024-04-09)

**editor or extension**: neovim with nvim-lspconfig and rust-tools

**code snippet to reproduce**: 

`main.rs`:
```rust
mod x { include!("x.rs"); }

fn main() {
    x::x();
}
```

`x.rs`:
```rust
pub fn x() { }
```

`Cargo.toml` (as generated by `cargo init`):
```toml
[package]
name = "ma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```

This code compiles, so it seems it's valid rust, yet rust-analyzer generates a diagnostic for file `x.rs`: "file not included in module tree" which does not seem correct.
