### ISSUE TITLE
Type inference fails when unpacking tuple

### ISSUE THREAD

**Issue by connorskees** [rust-lang/rust-analyzer#17067]
I didn't see any existing issues or PRs about this. In the below example, if you unpack a tuple, rather than explicitly accessing the fields, rust-analyzer fails to provide autocomplete and information on hover. 

```rs
// main.rs
use gimli::{EndianSlice, LittleEndian};

fn main() {
    let loader = |_| -> Result<_, ()> { Ok(EndianSlice::new(&[], LittleEndian)) };

    let dwarf = gimli::Dwarf::load(loader).unwrap();

    let mut iter = dwarf.units();
    let header = iter.next().unwrap().unwrap();
    let unit = dwarf.unit(header).unwrap();

    let mut entries = unit.entries();

    // fails
    let (_, entry) = entries.next_dfs().unwrap().unwrap();

    // works
    // let entry = entries.next_dfs().unwrap().unwrap().1;

    // unable to get autocomplete after typing `.` and hovering `tag` shows nothing
    entry.tag();
}
```

```toml
# Cargo.toml
[package]
name = "gimli-ra-test"
version = "0.1.0"
edition = "2021"

[dependencies]
gimli = "0.29.0"
```

https://github.com/rust-lang/rust-analyzer/assets/39542938/46516016-2649-45a9-8ed8-c223fc4f96c6
