### ISSUE TITLE
Wrong syntax highlight and definition of decl macro when working with `#[tokio::test]` proc-macro

### ISSUE THREAD

**Issue by Jisu-Woniu** [rust-lang/rust-analyzer#17196]
![screenshot](https://github.com/rust-lang/rust-analyzer/assets/31986081/870a9cde-9a5c-432b-a62f-2057c6b72b5c)

As is shown in the picture, the last `assert_eq!` macro got a incorrect definition and syntax highlight.

**rust-analyzer version**: 0.3.1950-standalone

**rustc version**: rustc 1.78.0 (9b00956e5 2024-04-29)

**editor or extension**: VS Code 1.89.0, rust-analyzer extension v0.3.1950 on Arch Linux

**relevant settings**: Don't remember

**code snippet to reproduce**: 

`src/lib.rs`

```rust
#[cfg(test)]
mod tests {

    #[tokio::test]
    async fn it_works() {
        assert_eq!(2, 2);
        assert_eq!(4, 4);
    }
}
```

`Cargo.toml`:

```toml
[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
```
