### ISSUE TITLE
No proc-macros present for crate

### ISSUE THREAD

**Issue by huntc** [rust-lang/rust-analyzer#17662]
**rust-analyzer version**:

rust-analyzer-2024-07-15

**rustc version**: (eg. output of `rustc -V`)

rustc 1.72.1 (d5c2e9c34 2023-09-13)

**editor or extension**

Zed 0.144.4
(also observed in VSC)

**relevant settings**

Using a .zed/settings.json file to help the editor locate its projects:

```json
{
  "lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "linkedProjects": ["configurator/backend/Cargo.toml"]
      }
    }
  }
}
```

Using a rust-toolchain.toml file:

```toml
[toolchain]
channel = "1.72.1"
components = [ "rustfmt", "clippy" ]
targets = [ "armv7-unknown-linux-musleabihf", "mipsel-unknown-linux-musl" ]
```

**repository link (if public, optional)**

Private repo.

**code snippet to reproduce**

Seeing the following; similar for all macros:

<img width="1074" alt="image" src="https://github.com/user-attachments/assets/f99d23ec-f4e3-480b-aac8-659b911c3c68">
