### ISSUE TITLE
fail to .await the inferred future type in inlay hints

### ISSUE THREAD

**Issue by tionway** [rust-lang/rust-analyzer#18014]
**rust-analyzer version**: 0.4.2093-standalone (9fd705195 2024-08-30)

**rustc version**: 1.80.1 (3f5fd8dd4 2024-08-06)

**editor or extension**:  VSCode, rust-analyzer v0.4.2093 (pre-release)

**relevant settings**: none

**repository link (if public, optional)**: none

type of `client` should just be `Client`, but ra fails to infer it, and leads to `let result: ! = ...`.

```rust
// add your code here
use mini_redis::{client, Result};

#[tokio::main]
async fn main() -> Result<()> {
    let mut client = client::connect("127.0.0.1:6379").await?;

    client.set("hello", "world".into()).await?;

    let result = client.get("hello").await?;

    println!("got value from the server; result={:?}", result);

    Ok(())
}
```
and dependencies

```toml
[dependencies]
tokio = { version = "1", features = [
    "full",
] }
mini-redis = "0.4"
```
