### ISSUE TITLE
can't find crate for `test` while using embassy

### ISSUE THREAD

**Issue by sunilkr** [rust-lang/rust-analyzer#18082]
I am getting an error message on [Ln 1, Col 1] of an almost empty project (image attached), while 0 error or warnings are produced with `cargo build`.

---

**rust-analyzer version**: rust-analyzer version: 0.3.2104-standalone (08c7bbc2d 2024-09-06)
**rustc version**: rustc 1.81.0 (eeb90cda1 2024-09-04)

**editor or extension**: VSCode (Windows 11)

**relevant settings**: N/A

**repository link (if public, optional)**: https://github.com/sunilkr/snakesy/tree/ra-error

**code snippet to reproduce**: https://gist.github.com/sunilkr/03f85c715411cf7de5d295257700ef73

---

`main.rs`
```rust
// Blinky with embassy

#![no_std]
#![no_main]

use embassy_executor::Spawner;

#[embassy_executor::main]
async fn main(_spawner: Spawner) {

}
```

`Cargo.toml`
```toml
[package]
name = "snakesy"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.8.0"
embassy-executor = { version = "0.6.0", features = ["defmt", "integrated-timers", "arch-cortex-m", "executor-thread"] }
embassy-time = { version = "0.3.2", features = ["defmt"] }
embassy-nrf = { version = "0.2.0", features = ["defmt", "nrf52833", "time-driver-rtc1", "gpiote", "nfc-pins-as-gpio"] }

defmt = "0.3"
defmt-rtt = "0.3"

cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.0"
panic-probe = { version = "0.3", features = ["print-defmt"] }
```

![image](https://github.com/user-attachments/assets/bf577bff-6735-4b31-a9c7-e4f10d7b9d54)
