### ISSUE TITLE
Run rust-analyzer in rosetta

### ISSUE THREAD

**Issue by filosganga** [rust-lang/rust-analyzer#18200]
Hello,

I have a rust library wrapping a C library that needs to be compiled on x86_64 architecture. I have managed to so on my m2, via the `arch -x86_64 zsh` from command line.

The issue is that rust-analyzer does not know about that. I have tried:

* Starting vscode within a x86_64 shell
* Start vscode from the arch command
* Adding arch -x86_64 as runnable

None of them has worked for me, any other suggestion?

Thanks

**Comment by filosganga** [comment]
In cargo.toml:

```toml
[build-dependencies]
bindgen = "0.69.4"
cc = "1.0"

[features]
default = ["aes", "sse4_2"]
aes = []
sse4_2 = []

[package.metadata.docs.rs]
rustc-cfg = ["target_feature=\"aes\"", "target_feature=\"sse4_2\""]
```

In build.rs:

```rust
    // Compile C files
    cc::Build::new()
        .file("mylib/mylib.c")
        .flag("-march=x86-64")
        .flag("-maes")
        .flag("-msse4.1")
        .flag("-O2")
        .compile("mylib");

    // Generate bindings
    let bindings = bindgen::Builder::default()
        .header("mylib/mylib.h")
        .clang_arg("-march=x86-64")
        .clang_arg("-maes")
        .clang_arg("-msse4.1")
        .default_enum_style(EnumVariation::Rust {
            non_exhaustive: false,
        })
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .generate()
        .expect("Unable to generate bindings");

    // Write bindings to file
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("Couldn't write bindings!");

    // Rerun build script if any of these files change
    println!("cargo:rerun-if-changed=mylib/mylib.h");
    println!("cargo:rerun-if-changed=mylib/mylib.c");
```

Then on shell:

```bash
arch -x86_64 zsh
cargo test --target x86_64-apple-darwin
```
