### ISSUE TITLE
Confusing error message when proc macro not built due to allTargets: false

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust-analyzer#18528]
**rust-analyzer version**: rust-analyzer version: 0.3.2188-standalone [/home/bjorn/.vscode/extensions/rust-lang.rust-analyzer-0.3.2188-linux-x64/server/rust-analyzer]

**rustc version**: rustc 1.82.0 (f6e511eec 2024-10-15)

**editor or extension**: VSCode

**relevant settings**:

```json
{
    "rust-analyzer.cargo.allTargets": false
}
```

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))

**code snippet to reproduce**:

```toml
#- Cargo.toml
[package]
name = "rust_analyzer_reproducer"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
serde = { version = "1.0.215", features = ["derive"] }
```

```rust
//- tests/foo.rs
#[derive(serde::Serialize)]
struct Foo;
```

and then after rust-analyzer has started make any change to `struct Foo;`. This will result in a "proc-macro crate build data is missing dylib path" error. This doesn't make it clear that this is because disabling `--all-targets` prevents `serde_derive` from getting built as it is a dev-dependency. It also shouldn't show up as an error, but closer to the diagnostic that is shown when build script building is disabled entirely though preferably also explaining why the proc-macro wasn't built.
