### ISSUE TITLE
how many memory do we really need?

### ISSUE THREAD

**Issue by creampnx-x** [rust-lang/rust-analyzer#18568]
# What happend?

2.6GB memory usage in only one VS Code window.

![Image](https://github.com/user-attachments/assets/0415512b-beec-4434-ba53-bcacfb4398de)

# My deps

```toml
[dependencies]
rocket = "0.5.0"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-native-tls"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
```
# My system

+ Ubuntu 24.04
+ Rust-analyzer Version 0.3.2196, Server Version 0.3.2196-standalone
+ rustc 1.82.0 (f6e511eec 2024-10-15)

# Question

what I can do? And is this normal?
