### ISSUE TITLE
Define our minimal supported rust version and warn if it is not met

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#18730]
As it keeps repeating in (sometimes annoying) ways when [we bump our minimum required rust version](https://github.com/rust-lang/rust-analyzer/issues/18705), we clearly should state whether the currently running toolchain is supported by the used rust-analyzer server or not, and in the case where it isn't warn the user and point them to either using the rustup component or upgrading their toolchain.

**Comment by shuffle2** [comment]
I arrived here from this blog: https://v5.chriskrycho.com/notes/rust-analyzer-version-via-rust-toolchain-toml/
I have a rust-toolchain.toml like:
```toml
[toolchain]
channel = "1.70"
targets = ["riscv32imc-unknown-none-elf"]
profile = "minimal"
components = ["rust-analyzer", "rustfmt", "clippy"]
```
(I just added "rust-analyzer", in hopes it pulls down the correct version)

This doesn't seem to work...while this does trigger rustup to download rust-analyzer, it downloads it for `rust-analyzer-x86_64-unknown-linux-gnu`, not `1.70` (although rustup does pull down the rest of the properly-versioned toolchain).

Is this supposed to work or am I doing something wrong?

I'd like to use rust-analyzer in vscode, and was hoping specifying it in the rust-toolchain.toml would be the most "proper" solution.
