### ISSUE TITLE
generated file changes via build.rs not picked up

### ISSUE THREAD

**Issue by pdeva** [rust-lang/rust-analyzer#18916]
we have some protobuf files that are built using `build.rs` in a create called `proto_defs` in our cargo workspace. when i make some changes like adding a new protobuf message to an existing .proto file, the compiler picks up the changes fine but rust-rover doesnt seem to recognize the newly generated files.

**rust-analyzer version**: rust-analyzer version: 0.3.2257-standalone

**rustc version**: rustc 1.84.0 (9fc6b4312 2025-01-07)

**editor or extension**: vscode. extension version 0.3.2257

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))

**code snippet to reproduce**: 

`build.rs`
```rust
use glob::glob;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut proto_files = Vec::new();
    for entry in glob("**/*.proto")? {
        proto_files.push(entry?.display().to_string());
    }
    let includes: [&str; 0] = [];
    tonic_build::configure()
        .compile_well_known_types(true)
        .compile_protos(proto_files.as_slice(), &includes)?;

    Ok(())
}


```

`tonic.rs`
``` rust
pub mod helloworld {
    pub mod svc {
        tonic::include_proto!("helloworld.svc");
    }
    pub mod lib {
        tonic::include_proto!("helloworld.lib");
    }
}
```

`cargo.toml`
```toml

[package]
name = "proto_defs"
version = "0.0.1"
edition = "2021"

[lib]
name = "proto_defs"
path = "tonic_defs.rs"
doctest = false

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }
[build-dependencies]
glob = { workspace = true }
tonic-build = { workspace = true }
```
