### ISSUE TITLE
Rust analyzer fails to parse windows crate for versions 0.58+

### ISSUE THREAD

**Issue by numonce** [rust-lang/rust-analyzer#18962]
Rust analyzer seems to fail to parse with windows crate from version 58 onwards. Version 57 is parsed fine. This only seems to be a bug when writing on linux to cross compile for windows. The program will still compile, but will error on the `cargo check` with 

```
error[E0432]: unresolved import `windows::Win32`
 --> src/main.rs:1:5
  |
1 | use windows::Win32;
  |     ^^^^^^^^^^^^^^ no `Win32` in the root

For more information about this error, try `rustc --explain E0432`.
```

rust-analyzer 1.84.0 (9fc6b43 2025-01-07)

rustc 1.84.0 (9fc6b4312 2025-01-07)

**code snippet to reproduce**: 
```rust
use windows::Win32;
fn main() {
    println!("Hello, world!");
}
```
```toml
[dependencies]
windows = { version = "0.59.0", features = ["Win32"] }
```

**Comment by Veykril** [comment]
How are you telling cargo to build for windows? Via the `--target` flag? Via `.cargo/config`?

**Comment by numonce** [comment]
Sorry for the late response. I'm building using the --target flag. Setting the `.cargo/config.toml` to 
```toml
[build]
target = "x86_64-pc-windows-gnu"
```
Resolves the described issue.
