### ISSUE TITLE
Cargo.toml file if mains to ".rs" rust analyzer doesn't work, changine main file to "_.rs" solves it.

### ISSUE THREAD

**Issue by hq-zyrosk** [rust-lang/rust-analyzer#19181]
**rust-analyzer version**: rust-analyzer version: 0.4.2309-standalone

**rustc version**: rustc 1.86.0-nightly (ef148cd7e 2025-02-12)

**editor or extension**: VSCode

**relevant settings**: none

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))

**code snippet to reproduce**: 
```rust
// any code of rust doesn't show editor token colors or hints if the Cargo.toml file has a lib which mains to ".rs" file, if I use "_.rs" as main file it works, next code if the Cargo.toml file I used.
```

```toml
[lib]
path = ".rs"
doctest = false

[package]
name = "en"
version = "1.1.1"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
libc = "0.2.169"
```
