### ISSUE TITLE
`unresolved extern crate` for rustc private crates for 2025-03-17 nightly

### ISSUE THREAD

**Issue by zjp-CN** [rust-lang/rust-analyzer#19503]
**rust-analyzer version**: rust-analyzer 1.87.0-nightly (43a2e9d 2025-03-17)

**rustc version**: rustc 1.87.0-nightly (43a2e9d2c 2025-03-17)

**editor or extension**: neovim

**relevant settings**: 

* `[package.metadata.rust-analyzer] rustc_private=true` in Cargo.toml
* `"rust-analyzer.rustc.source": "discover"` in settings.json

**code snippet to reproduce**: 

```rust
#![feature(rustc_private)]
extern crate stable_mir; // 👈 unresolved extern crate
fn main() {}
```

```toml
[toolchain]
channel = "nightly-2025-03-18" // change this to nightly-2025-04-01, the "unresolved extern crate" problem gone
components = ["llvm-tools", "rustc-dev", "rust-src", "rustfmt", "rust-analyzer"]
```

NOTE: I think this is likely a temporary regression in RA, because I've tested RA before or after 2025-03-17 version and found RA works well.

![Image](https://github.com/user-attachments/assets/c7f03746-0707-4030-93a1-c77cbcc23c1a)

![Image](https://github.com/user-attachments/assets/9e0307fa-d793-4db5-a516-c2004f82c731)
