### ISSUE TITLE
Explicitly select members in a workspace

### ISSUE THREAD

**Issue by eronnen** [rust-lang/rust-analyzer#19741]
If there is a workspace with multiple members (`crate1`, `crate2`) which use the same crate dependency (`crate3`) but `crate1` uses a feature `feature_a` and `crate2` doesn't, then `rust-analyzer` won't Identify code under `#[cfg(not(feature = "feature_a"))]`, even though `crate2` might use such code.

In order to solve this straightforwardly, it would be nice to have the option to either

1. Make rust-analyzer discover only members in `default-members`.
2. Define explicit members for rust-analyzer to discover, similar to the `rust-analyzer.linkedProjects` setting.

Example Cargo.toml:

```toml
[workspace]
resolver = "2"
members = [
    "crate1",
    "crate2",
]

default-members = [
    "crate2"
]

[workspace.dependencies]
crate3 = { path = "crate3", default-features = false }
```
