### ISSUE TITLE
High Memory Usage (2.5GB+) for Minimal Tauri 2 Project with `rust-analyzer`

### ISSUE THREAD

**Issue by savageKarl** [rust-lang/rust-analyzer#20028]
**Description:**
`rust-analyzer` consumes excessive memory (around 2.5GB) when opening a newly created, minimal Tauri 2 project in VS Code on Windows. This high memory usage persists even after `cargo clean` and VS Code restarts, and occurs with no other Rust projects open. This behavior is observed on a fresh Tauri 2 project created via `pnpm create tauri-app` with minimal dependencies, suggesting a potential performance issue or memory leak within `rust-analyzer` when handling Tauri 2 projects.

---

**Steps to Reproduce:**
1.  Ensure Rust toolchain and Tauri CLI are up to date.
2.  Create a new minimal Tauri 2 project using `pnpm create tauri-app` with default options (e.g., React + TypeScript, or similar minimal setup).
3.  Open the newly created project's root directory in Visual Studio Code. (e.g., if project name is `my-tauri-app`, open `my-tauri-app` in VS Code).
4.  Observe the `rust-analyzer` process memory usage via Windows Task Manager.

---

**Expected Behavior:**
For a minimal "Hello World" type project, `rust-analyzer`'s memory footprint should be significantly lower, typically in the range of a few hundred MBs to perhaps 1GB at most, not consistently around 2.5GB.

---

**Actual Behavior:**
Upon opening the minimal Tauri 2 project in VS Code, the `rust-analyzer` process memory usage quickly escalates and stabilizes at approximately **2500 MB (2.5 GB)**. This occurs consistently, even after running `cargo clean` and restarting VS Code.

---

**Environment Information:**

* **Operating System:** Microsoft Windows, Version 22H2 (OS Build 19045.5965)
* **VS Code Version:** 1.100.2 (system setup)
    * Commit: `848b80aeb52026648a8ff9f7c45a9b0a80641e2e`
    * Date: `2025-05-14T21:47:40.416Z`
    * Electron: `34.5.1`
    * Chromium: `132.0.6834.210`
    * Node.js: `20.19.0`
    * V8: `13.2.152.41-electron.0`
* **`rust-analyzer` Extension Version:** 0.3.2500 (Last Updated: 2025-06-16, 17:07:24)
* **`rustc` Version:** `rustc 1.87.0 (17067e9ac 2025-05-09)`
* **`pnpm tauri` CLI Version:** `tauri-cli 2.5.0`

---

**Relevant `Cargo.toml` (from the minimal project):**

```toml
# src-tauri/Cargo.toml
[package]
name = "tauri-issue-app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[lib]
name = "tauri_issue_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
```

---

**Minimal Reproducible Repository:**
A minimal project demonstrating this issue can be found here:
[https://github.com/savageKarl/tauri-issue-app](https://github.com/savageKarl/tauri-issue-app)

---

**Additional Notes:**
* The memory observation was done via Windows Task Manager.
* I have already tried `cargo clean` and restarting VS Code multiple times, but the memory usage for `rust-analyzer` remains consistently high (around 2.5GB).
* This issue occurs even with the most basic Tauri 2 setup, with no additional complex dependencies like `specta` or `tokio` (which were initially suspected in a larger project but verified not to be the sole cause). This points to a potential inherent high memory cost for `rust-analyzer` when analyzing Tauri 2 projects.

---
