### ISSUE TITLE
Unresolved reference when chaining after a function argument

### ISSUE THREAD

**Issue by dustypomerleau** [rust-lang/rust-analyzer#6735]
I've noticed that some methods can't be resolved if the previous function is passed a function call as argument:

```toml
# Cargo.toml

[package]
name = "minimal example"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = {version = "0.2", features = ["full"]}
warp = "0.2"
```

```rust
// main.rs

use warp::Filter;

#[tokio::main]
async fn main() {
    //  `map` resolves as method here:
    let home = warp::path::end().map(|| "home page");

    // `map` yields unresolvedReference here:
    let login = warp::path("login").and(warp::path::end()).map(|| "login");
    
    let routes = warp::get().and(home.or(login);
    warp::serve(routes).run(([127, 0, 0, 1], 3030)).await;
}
```
