### ISSUE TITLE
Macro error with futures::try_join!

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#6835]
Same as @jeromegn , I am still getting the error on the nightly version of rust-analyzer, in my case in a call to `futures::try_join!`.

_Originally posted by @Victor-Savu in https://github.com/rust-analyzer/rust-analyzer/issues/6716#issuecomment-743399274_

**Comment by peku33** [comment]
Same here.
This affect all futures macros, like select, join etc.

**Comment by edwin0cheng** [comment]
Maybe related to #6811

**Comment by flodiebold** [comment]
@Victor-Savu @peku33 Please check this again with the next nightly or current master.

**Comment by Victor-Savu** [comment]
Unfortunately I can still reproduce the problem. Here is a minimal reproduction:

> Extension version: 0.3.418-nightly

`cargo.toml`:
```toml
[package]
name = "rust-analyzer-error"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
futures = "0.3"
```

`main.rs`:
```rust
#[tokio::main]
async fn main() {
    futures::join!(
        async {
            println!("Hello, world!");
        },
        async {
            println!("Hello, world!");
        }
    );
}
```

I used `join!` instead of `try_join!` to keep the example as short as possible but the error is the same:
> could not resolve macro `$crate::try_join_internal`
